function [d sl]=init_dsl(o)

    % initialize the sl struct.
    sl=struct(...
        'b',int32(0),...
        'e',int32(0),...
        'others',int32(zeros(1,o.window)),...
        'adjusts',int16(zeros(1,o.window)),...
        'scalingdata',single(zeros(o.nch,o.window)),...
        'Tmat',single(zeros(o.window-1,3,o.nch)),...
        'clusterdata',int16(zeros(o.nch,o.window)),...
        'chosenTemplate',int16(zeros(1,o.nch)),...
        'template_scalings',single(zeros(1,o.nch)),...
        'template_adjusts',single(zeros(1,o.nch)),...
        'cluster_correlation',single(zeros(1,o.nch))...
        );
    
    
    % d = original data, data after 
    d.clean=single(zeros(o.nch,o.npnts));
    d.noise=single(zeros(o.nch,o.npnts));
    d.anc=single(zeros(o.nch,o.npnts));
    
